name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request:

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - name: Run ESLint and Stylelint
        run: npm run lint
  w3c_validator:
    needs: linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check HTML5
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: '.'
          # Can't recognize aspect-ratio rule
          css: false
          extra: --show-warnings
  bem_validator:
    needs: w3c_validator
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Check BEM
          uses: chvllad/bem-validator-action@v0.5
          with:
            html: '*.html'
